---
version: 2.1

executors:
  chart-releaser:
    docker:
      - image: quay.io/helmpack/chart-releaser:v1.2.0
    environment:
      LC_ALL: "C.UTF-8"
    resource_class: medium

commands:
  # build:
  #   steps:
  #     - run:
  #         command: apk add argocd
  #         name: Install JavaScript dependencies for Pulumi
  deploy:
    steps:
      - run:
          command: ./scripts/chart_publish.sh $APIKey
          name: Run the release script

jobs:
  release-chart:
    executor: chart-releaser
    steps:
      - checkout
      - deploy

workflows:
  releaser:
    jobs:
      - release-chart